export const GET_USER_DETAILS = '[User] GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = `[User] ${GET_USER_DETAILS}_SUCCESS`;
export const GET_USER_DETAILS_FAILURE = `[User] ${GET_USER_DETAILS}_FAILURE`;